### ISSUE TITLE
Feature: User can select where to go from home page.

### ISSUE THREAD

**Issue by avallonsmith** [avallonsmith/ajax-project#1]
## ⚙️ Feature

> ##### Users will begin on the home page. From there they can click "Search" to go to the search page, "Pokedex" to access the Pokedex page, and "My Team" to view the pokemon they have saved to their team.

## 📐 Functionality

> ##### By having a directory menu on the home page to the other web pages, the user can better navigate the website.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/96964291/164290713-31a43c45-3616-443c-8f8a-17ecf8d8503f.png)
![image](https://user-images.githubusercontent.com/96964291/164290733-ad9f07a3-14ba-4d43-befc-da12363e5467.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Go to search page from home page
- [x] Go to pokedex page from home page
- [x] Go to team page from home page
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
