### ISSUE TITLE
Feature: User can search for specific Pokemon.

### ISSUE THREAD

**Issue by avallonsmith** [avallonsmith/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will have the ability to search for a specific Pokemon using the search page.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Rather than having to scroll through the Pokedex until the Pokemon the user is looking for is found, they can search for specific Pokemon to better navigate through Pokedex.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/96964291/164293226-2b939881-ae5c-483a-b865-503f5262592a.png)
![image](https://user-images.githubusercontent.com/96964291/164293260-20ef69bb-982e-4159-bdf4-db81272cc3c1.png)
![image](https://user-images.githubusercontent.com/96964291/164293284-19893306-a491-4bc9-9c55-3564613a0fbb.png)
![image](https://user-images.githubusercontent.com/96964291/164293297-4bdfe624-e9e2-4b5e-92bf-d58e36c01801.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] ...
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
